name: geomx
channels:
  - conda-forge
  - bioconda
  - defaults
  - R
dependencies: 
  - conda-forge::r-base
  - conda-forge::r-tidyverse
  - conda-forge::r-dplyr
  - bioconda::bioconductor-nanostringnctools
  - bioconda::bioconductor-geomxtools

  - bioconda::bioconductor-fgsea
  - bioconda::bioconductor-spatialdecon
  - bioconda::r-immunedeconv
  - bioconda::snakemake

  - conda-forge::r-broom.mixed
  - conda-forge::r-cowplot
  - conda-forge::r-devtools
  - conda-forge::r-emmeans
  - conda-forge::r-ggforce
  - conda-forge::r-ggplotify
  - conda-forge::r-ggpubr
  - conda-forge::r-ggrepel
  - conda-forge::r-gridextra 
  - conda-forge::r-knitr
  - conda-forge::r-matrix
  - conda-forge::r-msigdbr
  - conda-forge::r-networkd3
  - conda-forge::r-officer
  - conda-forge::r-openxlsx
  - conda-forge::r-reshape2
  - conda-forge::r-rtsne
  - conda-forge::r-scales
  - conda-forge::r-shiny
  - conda-forge::r-umap
  - conda-forge::r-vegan
  - conda-forge::r-yaml